Signed-off-by: Maruko <6285343+Marukon@users.noreply.github.com>

diff --git a/.github/workflows/bubu-build.yml b/.github/workflows/bubu-build.yml
--- a/.github/workflows/bubu-build.yml
+++ b/.github/workflows/bubu-build.yml
@@ -26,7 +26,7 @@ env:
   ANDROID_FLUTTER_VERSION: "3.24.5"
   # for arm64 linux because official Dart SDK does not work
   FLUTTER_ELINUX_VERSION: "3.16.9"
-  TAG_NAME: "${{ inputs.upload-tag }}"
+  TAG_NAME: "'nightly'"
   VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
   # vcpkg version: 2025.08.27
   # If we change the `VCPKG COMMIT_ID`, please remember:
@@ -41,7 +41,7 @@ env:
   #signing keys env variable checks
   ANDROID_SIGNING_KEY: "${{ secrets.ANDROID_SIGNING_KEY }}"
   MACOS_P12_BASE64: "${{ secrets.MACOS_P12_BASE64 }}"
-  UPLOAD_ARTIFACT: "${{ inputs.upload-artifact }}"
+  UPLOAD_ARTIFACT: "'true'"
   SIGN_BASE_URL: "${{ secrets.SIGN_BASE_URL }}-2"
 
 jobs:
@@ -51,7 +51,7 @@ jobs:
   build-RustDeskTempTopMostWindow:
     uses: ./.github/workflows/third-party-RustDeskTempTopMostWindow.yml
     with:
-      upload-artifact: ${{ inputs.upload-artifact }}
+      upload-artifact: 'true'
       target: windows-2022
       configuration: Release
       platform: x64
@@ -92,15 +92,15 @@ jobs:
 
       - name: Bubu Customizations
         run: |
-          sed -i 's/rs-ny.rustdesk.com/${{ secrets.BUBU_SERVER_IP }}/g' libs/hbb_common/src/config.rs || true
-          sed -i 's/OeVuKk5nlHiXp+APNn0Y3pC1Iwpwn44JGqrQCsWqmBw=/${{ secrets.BUBU_SERVER_KEY }}/g' libs/hbb_common/src/config.rs || true
-          sed -i 's/RwLock::new("RustDesk".to_owned())/RwLock::new("RustDesk布布专用".to_owned())/g' libs/hbb_common/src/config.rs || true
-          sed -i 's/applicationId "com.carriez.rustdesk"/applicationId "com.marukon.desk"/g' flutter/android/app/build.gradle || true
-          find flutter/android -type f -exec sed -i 's/com.carriez.rustdesk/com.marukon.desk/g' {} + || true
-          find flutter/android -type f -exec sed -i 's/android:label="RustDesk"/android:label="RustDesk布布专用"/g' {} + || true
-          sed -i 's/L"RustDesk"/L"RustDesk布布专用"/g' flutter/windows/runner/main.cpp || true
-          sed -i 's/VALUE "ProductName", "RustDesk"/VALUE "ProductName", "RustDesk布布专用"/g' flutter/windows/runner/Runner.rc || true
-          sed -i 's/VALUE "FileDescription", "RustDesk"/VALUE "FileDescription", "RustDesk布布专用"/g' flutter/windows/runner/Runner.rc || true
+          sed -i "s|rs-ny.rustdesk.com|${{ secrets.BUBU_SERVER_IP }}|g" libs/hbb_common/src/config.rs || echo "Failed to set IP"
+          sed -i "s|OeVuKk5nlHiXp+APNn0Y3pC1Iwpwn44JGqrQCsWqmBw=|${{ secrets.BUBU_SERVER_KEY }}|g" libs/hbb_common/src/config.rs || echo "Failed to set Key"
+          sed -i 's|RwLock::new("RustDesk".to_owned())|RwLock::new("RustDesk布布专用".to_owned())|g' libs/hbb_common/src/config.rs || echo "Failed to set App Name"
+          sed -i 's|applicationId "com.carriez.flutter_hbb"|applicationId "com.marukon.desk"|g' flutter/android/app/build.gradle || echo "Failed to set package name build"
+          find flutter/android -type f -exec sed -i 's|com.carriez.flutter_hbb|com.marukon.desk|g' {} + || echo "Failed to set package name in android files"
+          find flutter/android -type f -name "*AndroidManifest.xml" -exec sed -i 's|android:label="RustDesk"|android:label="RustDesk布布专用"|g' {} + || echo "Failed to set Android label"
+          sed -i 's|L"RustDesk"|L"RustDesk布布专用"|g' flutter/windows/runner/main.cpp || true
+          sed -i 's|VALUE "ProductName", "RustDesk"|VALUE "ProductName", "RustDesk布布专用"|g' flutter/windows/runner/Runner.rc || true
+          sed -i 's|VALUE "FileDescription", "RustDesk"|VALUE "FileDescription", "RustDesk布布专用"|g' flutter/windows/runner/Runner.rc || true
         shell: bash
 
       - name: Restore bridge files
@@ -232,7 +232,7 @@ jobs:
 
       - name: Download RustDeskTempTopMostWindow artifacts
         uses: actions/download-artifact@master
-        if: ${{ inputs.upload-artifact }}
+        if: 'true'
         with:
           name: topmostwindow-artifacts
           path: "./rustdesk"
@@ -416,15 +416,15 @@ jobs:
 
       - name: Bubu Customizations
         run: |
-          sed -i 's/rs-ny.rustdesk.com/${{ secrets.BUBU_SERVER_IP }}/g' libs/hbb_common/src/config.rs || true
-          sed -i 's/OeVuKk5nlHiXp+APNn0Y3pC1Iwpwn44JGqrQCsWqmBw=/${{ secrets.BUBU_SERVER_KEY }}/g' libs/hbb_common/src/config.rs || true
-          sed -i 's/RwLock::new("RustDesk".to_owned())/RwLock::new("RustDesk布布专用".to_owned())/g' libs/hbb_common/src/config.rs || true
-          sed -i 's/applicationId "com.carriez.rustdesk"/applicationId "com.marukon.desk"/g' flutter/android/app/build.gradle || true
-          find flutter/android -type f -exec sed -i 's/com.carriez.rustdesk/com.marukon.desk/g' {} + || true
-          find flutter/android -type f -exec sed -i 's/android:label="RustDesk"/android:label="RustDesk布布专用"/g' {} + || true
-          sed -i 's/L"RustDesk"/L"RustDesk布布专用"/g' flutter/windows/runner/main.cpp || true
-          sed -i 's/VALUE "ProductName", "RustDesk"/VALUE "ProductName", "RustDesk布布专用"/g' flutter/windows/runner/Runner.rc || true
-          sed -i 's/VALUE "FileDescription", "RustDesk"/VALUE "FileDescription", "RustDesk布布专用"/g' flutter/windows/runner/Runner.rc || true
+          sed -i "s|rs-ny.rustdesk.com|${{ secrets.BUBU_SERVER_IP }}|g" libs/hbb_common/src/config.rs || echo "Failed to set IP"
+          sed -i "s|OeVuKk5nlHiXp+APNn0Y3pC1Iwpwn44JGqrQCsWqmBw=|${{ secrets.BUBU_SERVER_KEY }}|g" libs/hbb_common/src/config.rs || echo "Failed to set Key"
+          sed -i 's|RwLock::new("RustDesk".to_owned())|RwLock::new("RustDesk布布专用".to_owned())|g' libs/hbb_common/src/config.rs || echo "Failed to set App Name"
+          sed -i 's|applicationId "com.carriez.flutter_hbb"|applicationId "com.marukon.desk"|g' flutter/android/app/build.gradle || echo "Failed to set package name build"
+          find flutter/android -type f -exec sed -i 's|com.carriez.flutter_hbb|com.marukon.desk|g' {} + || echo "Failed to set package name in android files"
+          find flutter/android -type f -name "*AndroidManifest.xml" -exec sed -i 's|android:label="RustDesk"|android:label="RustDesk布布专用"|g' {} + || echo "Failed to set Android label"
+          sed -i 's|L"RustDesk"|L"RustDesk布布专用"|g' flutter/windows/runner/main.cpp || true
+          sed -i 's|VALUE "ProductName", "RustDesk"|VALUE "ProductName", "RustDesk布布专用"|g' flutter/windows/runner/Runner.rc || true
+          sed -i 's|VALUE "FileDescription", "RustDesk"|VALUE "FileDescription", "RustDesk布布专用"|g' flutter/windows/runner/Runner.rc || true
         shell: bash
 
       - name: Restore bridge files
